/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import modelo.Usuario;

/**
 *
 * @author Fabian
 */
public class Home extends javax.swing.JFrame {

    private static final int ADMIN = 1;
    private static final int USR = 2;
    
    Usuario usuario;
    
    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    public Home(Usuario usuario) {
        this.usuario = usuario;
        initComponents();
        this.setLocationRelativeTo(null);
        
        lblNombre.setText(this.usuario.getNombre());
        lblRol.setText(this.usuario.getNombre_tipo());
    
        if(usuario.getId_tipo() == ADMIN){
            //restricciones para el admin si hubiese alguna
        }else if(usuario.getId_tipo() == USR){
            menuProveedores.setVisible(false);
            menuItemAgrProd.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        lblNombre = new javax.swing.JLabel();
        lblRol = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuProductos = new javax.swing.JMenu();
        menuItemModProd = new javax.swing.JMenuItem();
        menuItemAgrProd = new javax.swing.JMenuItem();
        menuItemCatProd = new javax.swing.JMenuItem();
        menuProveedores = new javax.swing.JMenu();
        menuItemAgrProv = new javax.swing.JMenuItem();
        menuItemProv = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Home");
        setResizable(false);

        lblNombre.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        lblRol.setFont(new java.awt.Font("sansserif", 0, 14)); // NOI18N

        menuProductos.setText("Productos");

        menuItemModProd.setText("Modificar producto");
        menuProductos.add(menuItemModProd);

        menuItemAgrProd.setText("Agregar producto");
        menuProductos.add(menuItemAgrProd);

        menuItemCatProd.setText("Catálogo producto");
        menuProductos.add(menuItemCatProd);

        jMenuBar1.add(menuProductos);

        menuProveedores.setText("Proveedores");

        menuItemAgrProv.setText("Agregar proveedor");
        menuProveedores.add(menuItemAgrProv);

        menuItemProv.setText("Catalogo proveedor");
        menuProveedores.add(menuItemProv);

        jMenuBar1.add(menuProveedores);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRol)
                    .addComponent(lblNombre))
                .addContainerGap(372, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(lblNombre)
                .addGap(54, 54, 54)
                .addComponent(lblRol)
                .addContainerGap(165, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblRol;
    private javax.swing.JMenuItem menuItemAgrProd;
    private javax.swing.JMenuItem menuItemAgrProv;
    private javax.swing.JMenuItem menuItemCatProd;
    private javax.swing.JMenuItem menuItemModProd;
    private javax.swing.JMenuItem menuItemProv;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenu menuProveedores;
    // End of variables declaration//GEN-END:variables
}
