/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package app;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Fabian
 */
public class ABM extends javax.swing.JFrame {

    PreparedStatement ps;
    ResultSet res;
    
    /**
     * Creates new form persona
     */
    public ABM() {
        initComponents();
        txfId.setVisible(false);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblClave = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        lblDomicilio = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblCorreoElectronico = new javax.swing.JLabel();
        lblFechaDeNacimiento = new javax.swing.JLabel();
        lblGenero = new javax.swing.JLabel();
        txfFechaDeNacimiento = new javax.swing.JTextField();
        txfCorreoElectronico = new javax.swing.JTextField();
        txfTelefono = new javax.swing.JTextField();
        txfDomicilio = new javax.swing.JTextField();
        txfNombre = new javax.swing.JTextField();
        txfClave = new javax.swing.JTextField();
        cbxGenero = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txfId = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        lblId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABM personas");
        setResizable(false);

        lblClave.setText("Clave");

        lblNombre.setText("Nombre");

        lblDomicilio.setText("Domicilio");

        lblTelefono.setText("Teléfono");

        lblCorreoElectronico.setText("Correo Electrónico");

        lblFechaDeNacimiento.setText("Fecha de Nacimiento");

        lblGenero.setText("Género");

        txfClave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfClaveActionPerformed(evt);
            }
        });

        cbxGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecciona", "Femenino", "Masculino" }));

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txfId.setEnabled(false);

        btnBuscar.setText("Buscar por clave");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        lblId.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        lblId.setText("ABM personas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblId)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(lblClave)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(txfClave, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(73, 73, 73))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaDeNacimiento)
                            .addComponent(lblCorreoElectronico)
                            .addComponent(lblGenero)
                            .addComponent(lblTelefono)
                            .addComponent(lblDomicilio)
                            .addComponent(lblNombre))
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txfNombre)
                            .addComponent(txfDomicilio)
                            .addComponent(txfTelefono)
                            .addComponent(txfCorreoElectronico)
                            .addComponent(txfFechaDeNacimiento)
                            .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnBuscar)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(39, 39, 39)
                        .addComponent(btnModificar)
                        .addGap(45, 45, 45)
                        .addComponent(btnEliminar)
                        .addGap(39, 39, 39)
                        .addComponent(btnLimpiar)
                        .addGap(20, 20, 20))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblId)
                    .addComponent(txfId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblClave)
                    .addComponent(txfClave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombre)
                    .addComponent(txfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDomicilio)
                    .addComponent(txfDomicilio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(txfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCorreoElectronico)
                    .addComponent(txfCorreoElectronico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaDeNacimiento)
                    .addComponent(txfFechaDeNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenero))
                .addGap(29, 29, 29)
                .addComponent(btnBuscar)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnLimpiar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        Connection connection;
        
        try {
            connection = new SQLConnection().getConnection();
            
            ps = connection.prepareStatement("INSERT INTO persona(clave, nombre, domicilio, telefono, correo_electronico, fecha_nacimiento, genero) VALUES(?, ?, ?, ?, ?, ?, ?)");
            ps.setString(1, txfClave.getText());
            ps.setString(2, txfNombre.getText());
            ps.setString(3, txfDomicilio.getText());
            ps.setString(4, txfTelefono.getText());
            ps.setString(5, txfCorreoElectronico.getText());
            ps.setDate(6, Date.valueOf(txfFechaDeNacimiento.getText()));
            ps.setString(7, cbxGenero.getSelectedItem().toString());
            
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "Persona guardada");
            }else{
                JOptionPane.showMessageDialog(null, "Error al guardar persona");
            }
            
            vaciarCampos();
            
        } catch(SQLException | HeadlessException e) {
            Logger.getLogger(ABM.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
        Connection connection;
        
        try{
            connection = new SQLConnection().getConnection();
            ps = connection.prepareStatement("SELECT * FROM persona WHERE clave = ?");
            ps.setString(1, txfClave.getText());
            
            res = ps.executeQuery();
            if(res.next()){
                txfId.setText(res.getString("id"));
                txfClave.setText(res.getString("clave"));
                txfNombre.setText(res.getString("nombre"));
                txfDomicilio.setText(res.getString("domicilio"));
                txfTelefono.setText(res.getString("telefono"));
                txfCorreoElectronico.setText(res.getString("correo_electronico"));
                txfFechaDeNacimiento.setText(res.getString("fecha_nacimiento"));
                cbxGenero.setSelectedItem(res.getString("genero"));
                
                btnGuardar.setEnabled(false);
                btnModificar.setEnabled(true);
                btnEliminar.setEnabled(true);
            }else{
                JOptionPane.showMessageDialog(null, "No existe una persona con esa clave");
                vaciarCampos();
            }
        }catch(SQLException | HeadlessException e){
            Logger.getLogger(ABM.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:
        Connection connection;
        
        try {
            connection = new SQLConnection().getConnection();
            
            ps = connection.prepareStatement("UPDATE persona SET clave = ?, nombre = ?, domicilio = ?, telefono = ?, correo_electronico = ?, fecha_nacimiento = ?, genero = ? WHERE id = ?");
            ps.setString(1, txfClave.getText());
            ps.setString(2, txfNombre.getText());
            ps.setString(3, txfDomicilio.getText());
            ps.setString(4, txfTelefono.getText());
            ps.setString(5, txfCorreoElectronico.getText());
            ps.setDate(6, Date.valueOf(txfFechaDeNacimiento.getText()));
            ps.setString(7, cbxGenero.getSelectedItem().toString());
            ps.setString(8, txfId.getText());
            
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "Persona modificada");
            }else{
                JOptionPane.showMessageDialog(null, "Error al modificar persona");
            }
            
            vaciarCampos();
            
            btnGuardar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            
        } catch(SQLException | HeadlessException e) {
            Logger.getLogger(ABM.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        Connection connection;
        
        try {
            connection = new SQLConnection().getConnection();
            
            ps = connection.prepareStatement("DELETE FROM persona WHERE id = ?");
            ps.setInt(1, Integer.parseInt(txfId.getText()));
            
            if(ps.executeUpdate() > 0){
                JOptionPane.showMessageDialog(null, "Persona eliminada");
            }else{
                JOptionPane.showMessageDialog(null, "Error al eliminar persona");
            }
            
            vaciarCampos();
            
            btnGuardar.setEnabled(true);
            btnModificar.setEnabled(false);
            btnEliminar.setEnabled(false);
            
        } catch(SQLException | NumberFormatException | HeadlessException e) {
            Logger.getLogger(ABM.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        vaciarCampos();
        btnGuardar.setEnabled(true);
        btnModificar.setEnabled(false);
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void txfClaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfClaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfClaveActionPerformed

    private void vaciarCampos(){
        txfClave.setText(null);
        txfNombre.setText(null);
        txfDomicilio.setText(null);
        txfTelefono.setText(null);
        txfCorreoElectronico.setText(null);
        txfFechaDeNacimiento.setText(null);
        cbxGenero.setSelectedIndex(0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ABM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ABM().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JComboBox<String> cbxGenero;
    private javax.swing.JLabel lblClave;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblDomicilio;
    private javax.swing.JLabel lblFechaDeNacimiento;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txfClave;
    private javax.swing.JTextField txfCorreoElectronico;
    private javax.swing.JTextField txfDomicilio;
    private javax.swing.JTextField txfFechaDeNacimiento;
    private javax.swing.JTextField txfId;
    private javax.swing.JTextField txfNombre;
    private javax.swing.JTextField txfTelefono;
    // End of variables declaration//GEN-END:variables
}
